service: sls-sharp

provider:
    name: aws
    runtime: nodejs6.10
    region: eu-central-1

plugins:
    - serverless-plugin-typescript
    - serverless-apigwy-binary

package:
    excludeDevDependencies: false

functions:

    test:
        handler: src/handler.test
        events:
            - http:
                path: '{proxy+}'
                method: get
                contentHandling: CONVERT_TO_BINARY
