service: sls-sharp
provider:
    name: aws
    runtime: nodejs6.10
    profile: default
    stage: dev
    region: eu-central-1

    environment:
        BUCKET: "sls-sharp"
        SLS_DEBUG: "*"

    iamRoleStatements:
        - Effect: Allow
          Action:
            - s3:GetObject
          Resource: "arn:aws:s3:::sls-sharp/*"

custom:
    webpackIncludeModules: true

functions:
    transform:
        handler: handler.transform
        events:
            - http:
                path: '{proxy+}'
                method: get
                contentHandling: CONVERT_TO_BINARY

plugins:
    - serverless-webpack
    - serverless-offline
    - serverless-apigwy-binary

package:
    excludeDevDependencies: false
